In [258]:
import os
import numpy as np

**ques1**

 Create a 5 × 5 NumPy matrix containing numbers from 1 to 25 and 
print: 
○ The first row 
○ The last column 
○ The diagonal elements 

<!-- ques.1..... -->

In [259]:
arr=np.arange(1,26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [260]:
arr=arr.reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [261]:
arr[0]

array([1, 2, 3, 4, 5])

In [262]:
arr[:,-1]

array([ 5, 10, 15, 20, 25])

In [263]:
np.diag(arr)

array([ 1,  7, 13, 19, 25])

<!-- ques 2 ...... -->

*ques2*

Create two 3 × 3 matrices and perform matrix addition, subtraction, 
and matrix multiplication. 

In [264]:
arr=np.arange(0,9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [265]:
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [266]:
arr1=np.arange(0,9)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [267]:
arr1=arr1.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [268]:
print(arr+arr1)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [269]:
print(arr-arr1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [270]:
print(np.dot(arr, arr1))    #it is use for multiplication in numpy and @ also use for multiplication here we cannot use * operator 

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


*ques3*

Create a NumPy array of numbers from 1 to 100 and print all numbers 
divisible by 3 using Boolean indexing. 

<!-- ques 3.... -->

In [271]:
arr=np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [272]:
bool_arr=arr % 3 == 0

In [273]:
print(bool_arr)

[False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False]


In [274]:
print(arr[bool_arr])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


*ques4*

 Create a 4 × 4 matrix and replace all even numbers with 0. 

<!-- ques .....4 -->

In [275]:
arr=np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [276]:
arr=arr.reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [277]:
arr[arr % 2 == 0] = 0
print(arr)


[[ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]]


*ques5*

Create a 5 × 5 matrix of random integers and find: Maximum value ,Minimum value , Mean , Median 

<!-- ques 5... -->

In [278]:
arr=np.arange(25,50)
arr

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])

In [279]:
arr=arr.reshape(5,5)
arr


array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [280]:
arr.max()

np.int64(49)

In [281]:
arr.min()

np.int64(25)

In [282]:
arr.mean()

np.float64(37.0)

In [283]:
median = np.median(arr)
print(median)

37.0


<!-- ques 6 -->

<!-- ques 6 -->

*ques 6*

Create a NumPy array containing 20 random numbers and sort it in 
ascending and descending order.

In [284]:
arr=np.random.randint(10,80,20)
arr

array([55, 73, 32, 33, 55, 39, 77, 43, 22, 69, 54, 19, 62, 59, 79, 43, 23,
       51, 24, 60], dtype=int32)

In [285]:
arr.sort()
arr

array([19, 22, 23, 24, 32, 33, 39, 43, 43, 51, 54, 55, 55, 59, 60, 62, 69,
       73, 77, 79], dtype=int32)

In [286]:
print(np.sort(arr)[::-1])

[79 77 73 69 62 60 59 55 55 54 51 43 43 39 33 32 24 23 22 19]


<!-- ques 7-->

**ques 8**

Create a NumPy array of 20 elements and reshape it into: 
 4 × 5 matrix , 2 × 10 matrix ,5 × 4 matrix 

In [287]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [288]:
arr=arr.reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

<!-- ques 7 -->

In [289]:
arr=arr.reshape(2,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [290]:
arr=arr.reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

ques9

Create a 5 × 5 matrix and calculate the sum of: 
, Each row 
,Each column 

In [291]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [292]:
arr=arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [293]:
arr=np.sum(arr, axis=1)
arr

array([ 10,  35,  60,  85, 110])

In [294]:
arr= np.sum(arr, axis=0)
arr

np.int64(300)

*ques 10*

Create two arrays and find all common elements between them.

In [295]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

result = np.intersect1d(arr1, arr2)

print(result)

[3 4 5]


*ques 12*

Create a dataset of students' marks using a NumPy array and find: 
● Highest marks 
● Lowest marks 
● Average marks 
● Students scoring above average 

In [296]:
marks = np.array([75, 82, 90, 65, 88, 70, 95])

highest = np.max(marks)
lowest = np.min(marks)
average = np.mean(marks)

above_average = marks[marks > average]

print(highest)
print(lowest)
print( average)
print(above_average)

95
65
80.71428571428571
[82 90 88 95]


*ques 7*

Create a 6 × 6 matrix and print: 
○ Main diagonal 
○ Upper triangular part 
○ Lower triangular part

In [ ]:
arr = np.arange(1, 37)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [298]:
arr=arr.reshape(6, 6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [299]:
print("diagonal",np.diag(arr))
print("upper tringular ",np.triu(arr))
print("lower tringular",np.tril(arr))

diagonal [ 1  8 15 22 29 36]
upper tringular  [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
lower tringular [[ 1  0  0  0  0  0]
 [ 7  8  0  0  0  0]
 [13 14 15  0  0  0]
 [19 20 21 22  0  0]
 [25 26 27 28 29  0]
 [31 32 33 34 35 36]]


*ques 11*

Create a 5 × 5 matrix and find the position (row and column index) 
of the largest element. 

In [300]:
arr = np.arange(1, 26)
arr



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [301]:
arr=arr.reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [304]:
print("Largest Element", np.max(arr))
print("position", np.where(arr == np.max(arr)))

Largest Element 25
position (array([4]), array([4]))
